/* Generated by tools/fontgen/reindex.py — do not edit.
 * Regenerated whenever a font is added or removed.
 */
#pragma once

#include "moth_font_14.h"
#include "moth_font_20.h"
#include "moth_font_48.h"
#include "moth_font_72.h"

/* Smallest first, which is what lets font_for pick in one pass. */
static const moth_font *const kFaces[] = {
    &moth_font_14, /* 14px */
    &moth_font_20, /* 20px */
    &moth_font_48, /* 48px */
    &moth_font_72, /* 72px */
};
static const int kFaceCount = (int)(sizeof kFaces / sizeof kFaces[0]);
