#!/usr/bin/env python3
"""Turns a TTF into a moth bitmap font.

Nothing parses a font file on the device. A glyph is a small bitmap plus the
metrics needed to place it, generated here and compiled in — the same approach
LVGL takes, and for the same reason: a vector rasterizer is far more code and
far more time than an embedded panel wants to spend on a label.

Anti-aliasing is the whole point. Each pixel stores an alpha rather than an
on/off bit, so 4 bits per pixel gives sixteen levels of coverage and the edges
stop looking like stairs. That costs four times a bitonal font, which is why
you subset: pass --chars with only what you actually draw.

    python3 tools/fontgen/fontgen.py Inter.ttf 72 \\
        --chars '0123456789:' --name clock72 -o packages/moth/fonts/clock72.h

Metrics follow FreeType's model, since that is what Pillow reports:
  adv_w   how far the pen moves after this glyph
  box_w/h the bitmap's size, which is only the inked part
  ofs_x/y where that bitmap sits relative to the pen and the baseline
"""

import argparse
import os
import subprocess
import sys

from PIL import Image, ImageDraw, ImageFont

ASCII = "".join(chr(c) for c in range(32, 127))


def quantize(value: int, bpp: int) -> int:
    """8-bit coverage down to `bpp` bits, keeping 0 and full opacity exact."""
    levels = (1 << bpp) - 1
    return (value * levels + 127) // 255


def pack_row(alphas, bpp: int) -> bytes:
    """Packs one row of quantized alphas, high nibble first for 4bpp."""
    per_byte = 8 // bpp
    out = bytearray()
    for i in range(0, len(alphas), per_byte):
        byte = 0
        for j in range(per_byte):
            value = alphas[i + j] if i + j < len(alphas) else 0
            byte = (byte << bpp) | value
        out.append(byte)
    return bytes(out)


def render_glyph(font, ch, bpp):
    """Returns (bitmap bytes, box_w, box_h, ofs_x, ofs_y, adv_w)."""
    adv = font.getlength(ch)
    bbox = font.getbbox(ch)  # (x0, y0, x1, y1) relative to the pen at the top
    if bbox is None:
        return b"", 0, 0, 0, 0, int(round(adv))

    x0, y0, x1, y1 = bbox
    box_w, box_h = x1 - x0, y1 - y0
    if box_w <= 0 or box_h <= 0:  # space and friends have no ink
        return b"", 0, 0, 0, 0, int(round(adv))

    # Draw into a canvas large enough that nothing clips, then take the box.
    pad = 4
    img = Image.new("L", (box_w + pad * 2, box_h + pad * 2), 0)
    ImageDraw.Draw(img).text((pad - x0, pad - y0), ch, font=font, fill=255)
    img = img.crop((pad, pad, pad + box_w, pad + box_h))

    data = bytearray()
    px = img.load()
    for y in range(box_h):
        row = [quantize(px[x, y], bpp) for x in range(box_w)]
        data += pack_row(row, bpp)

    return bytes(data), box_w, box_h, x0, y0, int(round(adv))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("ttf")
    ap.add_argument("size", type=int, help="pixel size")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--name", required=True, help="C identifier for the font")
    ap.add_argument("--chars", default=ASCII)
    ap.add_argument("--bpp", type=int, default=4, choices=[1, 2, 4, 8])
    ap.add_argument("--weight", help="named instance of a variable font, e.g. Bold")
    ap.add_argument("--no-reindex", action="store_true",
                    help="skip rebuilding the font registry")
    args = ap.parse_args()

    font = ImageFont.truetype(args.ttf, args.size)
    if args.weight:
        try:
            font.set_variation_by_name(args.weight)
        except Exception as exc:  # a static font, or no such instance
            print(f"fontgen: {exc}", file=sys.stderr)
            sys.exit(1)

    chars = sorted(set(args.chars))
    first, last = ord(chars[0]), ord(chars[-1])
    if last - first > 255:
        sys.exit("fontgen: the character range must fit in one contiguous byte span")

    ascent, descent = font.getmetrics()
    line_height = ascent + descent

    # A contiguous table indexed by code point keeps lookup to one subtraction;
    # characters not asked for get an empty glyph.
    blob = bytearray()
    entries = []
    for cp in range(first, last + 1):
        ch = chr(cp)
        if ch not in chars:
            entries.append((0, 0, 0, 0, 0, 0))
            continue
        bitmap, w, h, ox, oy, adv = render_glyph(font, ch, args.bpp)
        entries.append((len(blob), adv, w, h, ox, oy))
        blob += bitmap

    name = args.name
    with open(args.out, "w") as f:
        f.write(f"/* Generated by tools/fontgen/fontgen.py — do not edit.\n"
                f" * source: {args.ttf.split('/')[-1]}  size: {args.size}px  "
                f"bpp: {args.bpp}\n"
                f" * characters: U+{first:04X}..U+{last:04X}\n */\n")
        f.write("#pragma once\n#include \"moth_font.h\"\n\n")

        f.write(f"static const uint8_t {name}_bitmap[] = {{\n")
        for i in range(0, len(blob), 16):
            row = ", ".join(f"0x{b:02X}" for b in blob[i:i + 16])
            f.write(f"  {row},\n")
        f.write("};\n\n")

        f.write(f"static const moth_glyph {name}_glyphs[] = {{\n")
        for (off, adv, w, h, ox, oy) in entries:
            f.write(f"  {{{off}, {adv}, {w}, {h}, {ox}, {oy}}},\n")
        f.write("};\n\n")

        f.write(f"static const moth_font {name} = {{\n"
                f"  \"{name}\", {args.size}, {line_height}, {ascent}, {args.bpp},\n"
                f"  0x{first:02X}, 0x{last:02X},\n"
                f"  {name}_glyphs, {name}_bitmap,\n"
                f"}};\n")

    print(f"{args.out}: {len(chars)} glyphs, {len(blob)} bytes of bitmap, "
          f"line height {line_height}")

    # Adding a font should be one command, so the registry the renderer reads
    # is rebuilt here rather than left as a hand edit to remember.
    if not args.no_reindex:
        reindex = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "reindex.py")
        subprocess.run([sys.executable, reindex], check=False)


if __name__ == "__main__":
    main()
