#!/usr/bin/env python3
"""Rebuilds the font registry from whatever is in moth_render/src/fonts.

fontgen writes one header per face. Something still has to tell the renderer
those faces exist, and making that a hand edit to text.cpp meant adding a font
was three steps, two of them easy to forget. This regenerates the index, so
adding or deleting a face is only ever "generate, or delete the file".

Run directly, or let fontgen call it — it does so after every generate.
"""

import glob
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
FONT_DIR = os.path.normpath(os.path.join(HERE, "..", "..", "moth_render", "src", "fonts"))

# `static const moth_font NAME = {\n  "NAME", SIZE, ...`
DECL = re.compile(
    r"static\s+const\s+moth_font\s+(\w+)\s*=\s*\{\s*\"[^\"]*\"\s*,\s*(\d+)\s*,",
    re.S,
)


def main():
    faces = []
    for path in sorted(glob.glob(os.path.join(FONT_DIR, "*.h"))):
        if os.path.basename(path) == "registry.h":
            continue
        text = open(path).read()
        m = DECL.search(text)
        if not m:
            print(f"reindex: {os.path.basename(path)} has no moth_font — skipped",
                  file=sys.stderr)
            continue
        faces.append((int(m.group(2)), m.group(1), os.path.basename(path)))

    if not faces:
        sys.exit("reindex: no fonts found in moth_render/src/fonts")

    # font_for() walks this looking for the largest face that fits, so keeping
    # it ordered small to large is what makes that a single pass.
    faces.sort()

    out = os.path.join(FONT_DIR, "registry.h")
    with open(out, "w") as f:
        f.write("/* Generated by tools/fontgen/reindex.py — do not edit.\n"
                " * Regenerated whenever a font is added or removed.\n */\n")
        f.write("#pragma once\n\n")
        for _, _, header in faces:
            f.write(f'#include "{header}"\n')
        f.write("\n/* Smallest first, which is what lets font_for pick in one pass. */\n")
        f.write("static const moth_font *const kFaces[] = {\n")
        for size, name, _ in faces:
            f.write(f"    &{name}, /* {size}px */\n")
        f.write("};\n")
        f.write("static const int kFaceCount = "
                "(int)(sizeof kFaces / sizeof kFaces[0]);\n")

    print(f"{out}: {len(faces)} faces — "
          + ", ".join(f"{n} ({s}px)" for s, n, _ in faces))


if __name__ == "__main__":
    main()
