import 'dart:io';

import 'package:mothc/src/compiler.dart';
import 'package:test/test.dart';

/// Compiles each test/cases/*.dart and runs it on the VM, comparing output to
/// the matching .out file.
///
/// The expectations for pure-computation cases are generated by the real Dart
/// SDK (`dart arithmetic.dart > arithmetic.out`), so these tests assert that
/// moth agrees with Dart itself — not merely with its own past behavior.
void main() {
  final repoRoot = Directory.current.path.endsWith('tools/mothc')
      ? Directory.current.parent.parent.path
      : Directory.current.path;
  final casesDir = Directory('$repoRoot/test/cases');
  final mothrun = File('$repoRoot/build/vm/mothrun');

  if (!mothrun.existsSync()) {
    test('vm is built', () {
      fail('build/vm/mothrun not found — run: cmake -B build . && '
          'cmake --build build');
    });
    return;
  }

  final cases = casesDir
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  for (final source in cases) {
    final name = source.uri.pathSegments.last.replaceAll('.dart', '');
    final expectedFile = File('${source.path.replaceAll('.dart', '')}.out');

    // A case may ship a .args file with extra simulator flags (fake analog
    // readings, fake I2C devices) so peripheral behavior is testable too.
    final argsFile = File('${source.path.replaceAll('.dart', '')}.args');
    final extraArgs = argsFile.existsSync()
        ? argsFile.readAsStringSync().trim().split(RegExp(r'\s+'))
        : const <String>[];

    test(name, () {
      final blob =
          Compiler(source.path, source.readAsStringSync()).compile().blob;
      final tmp = File('${Directory.systemTemp.path}/moth_test_$name.mothb')
        ..writeAsBytesSync(blob);

      final result =
          Process.runSync(mothrun.path, [tmp.path, '--quiet', ...extraArgs]);
      expect(result.exitCode, 0, reason: 'stderr: ${result.stderr}');
      expect(result.stdout, expectedFile.readAsStringSync());
      tmp.deleteSync();
    });
  }

  test('blink produces the expected pin trace', () {
    final source = File('$repoRoot/examples/blink.dart');
    final blob =
        Compiler(source.path, source.readAsStringSync()).compile().blob;
    final tmp = File('${Directory.systemTemp.path}/moth_test_blink.mothb')
      ..writeAsBytesSync(blob);

    final result =
        Process.runSync(mothrun.path, [tmp.path, '--stop-after', '2000']);
    expect(result.exitCode, 0, reason: 'stderr: ${result.stderr}');
    expect(result.stdout, '''
[     0ms] pin 38 -> output
[     0ms] pin 38 = HIGH
[   500ms] pin 38 = low
[  1000ms] pin 38 = HIGH
[  1500ms] pin 38 = low
-- stopped after 2000ms (simulated) --
''');
    tmp.deleteSync();
  });
}
