#ifndef MOTH_FONT_H
#define MOTH_FONT_H

/* A bitmap font, generated by tools/fontgen/fontgen.py.
 *
 * Each glyph stores coverage rather than on/off pixels, so text is
 * antialiased without a rasterizer: the stored value is the alpha the painter
 * blends with. Four bits gives sixteen levels, which is enough that edges stop
 * reading as stairs, and costs four times a bitonal font — hence subsetting.
 *
 * Metrics follow FreeType's model. The pen sits on the baseline; a glyph's
 * bitmap covers only its inked box, placed by ofs_x/ofs_y relative to that
 * pen, and the pen then advances by adv_w. That is what gives proportional
 * spacing, which a fixed grid cannot.
 */

#include <stddef.h>
#include <stdint.h>

typedef struct {
  /* Into the font's bitmap blob. 32 bits because a full ASCII face at 72px is
   * already ~99KB: as uint16_t the tail of the table wrapped, and glyphs read
   * from the wrong place in the blob with no warning in a C build. */
  uint32_t bitmap_offset;
  uint8_t adv_w;          /* how far the pen moves afterwards */
  uint8_t box_w, box_h;   /* the inked box, which may be empty */
  int8_t ofs_x, ofs_y;    /* where that box sits, from the pen and the top */
} moth_glyph;

typedef struct {
  const char *name;
  uint8_t size;        /* the pixel size it was generated at */
  uint8_t line_height; /* ascent + descent, which exceeds size */
  uint8_t bpp;
  uint8_t first, last; /* the contiguous code point range covered */
  const moth_glyph *glyphs;
  const uint8_t *bitmap;
} moth_font;

/* Coverage of one pixel, 0..255, whatever the font's bit depth. */
static inline uint8_t moth_glyph_alpha(const moth_font *f, const moth_glyph *g,
                                       int x, int y) {
  const int per_byte = 8 / f->bpp;
  const int stride = (g->box_w + per_byte - 1) / per_byte;
  const uint8_t byte = f->bitmap[g->bitmap_offset + (size_t)y * stride + x / per_byte];
  const int shift = (per_byte - 1 - (x % per_byte)) * f->bpp;
  const int levels = (1 << f->bpp) - 1;
  const int value = (byte >> shift) & levels;
  return (uint8_t)((value * 255) / levels);
}

#endif /* MOTH_FONT_H */
